[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

# SPA fallback so client-side routing works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
